# Generated by Django 6.0.3 on 2026-03-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Pakia picha (PNG/JPG) au PDF ya cheti hapa', null=True, upload_to='certificates/uploads/', verbose_name='Pakia Faili la Cheti'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID ya Cheti'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course_name',
            field=models.CharField(max_length=150, verbose_name='Jina la Kozi'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(auto_now_add=True, verbose_name='Tarehe ya Kutolewa'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code'),
        ),
    ]
